[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "w4b"
authors = [{name = "Squadra", email = "contato@squadra.com.br"}]
dynamic = ["version", "description"]
